### ISSUE TITLE
update JSONXOP

### ISSUE THREAD

**Issue by ukos-git** [byte-physics/language-igor#14]
```igorpro
JSON_Parse(wavenote, ignoreErr = 1)
```

```igorpro
JSONXOP_Dump jsonID
```

**Comment by t-b** [comment]
@ukos-git Would it be worthwhile to figure out in a generic way if it is an operation?

A regex could look like

```regexp
[A-Za-z_]+(\/[[A-Za-z].* |$)
```

**Comment by ukos-git** [comment]
I don't think, that regex will work. It looks too simple. From a quick look, I think

* it will not catch multiple flags
* it will not catch nested expressions
* the line end character is disturbing further processings

```igor
Make/N=(DimSize(wv, 0))/O/T root:wave/WAVE=wv = MyFunction(p) + str2num(p)
```

But you could give it a try. The relevant pattern goes in here:

https://github.com/byte-physics/language-igor/blob/9e15042d5ff20700ddf9a349380c04013dce85d4/igorpro.YAML-tmLanguage#L198-L210

personally, I think, editing the fixed list of operations is quicker to do than messing with the regexp and more failsafe.

**Comment by ukos-git** [comment]
you will have to search for line start to differntiate something like

```igorpro
Variable operation = 1
a = operation/1
```

**Comment by t-b** [comment]
@ukos-git

Yeep, you are right. This does not work.

**Comment by ukos-git** [comment]
```igor
Variable Make = 1
Variable F = 2
Variable result
result = Make/F
```

btw. I am also not searching for the line start which should be fixed.

**Comment by t-b** [comment]
@ukos-git

Which operation can be used on the RHS of `=` ? I can't think of one right now.

**Comment by ukos-git** [comment]
which is why operations should always start at the beginning of the line, or?

**Comment by ukos-git** [comment]
btw. Igor Compiler is recognizing it correctly but coloring is wrong:

![Screenshot from 2019-08-30 17-01-37](https://user-images.githubusercontent.com/16167358/64031000-eebd2300-cb47-11e9-8675-7083d2b263ce.png)

**Comment by t-b** [comment]
> which is why operations should always start at the beginning of the line, or?

Exactly.
