### ISSUE TITLE
Highlighting broken on GitHub 

### ISSUE THREAD

**Issue by ukos-git** [byte-physics/language-igor#16]
I think, one of the latest PRs broke the Highlighting on Github. We need tests here.

**Comment by t-b** [comment]
https://github.com/github/linguist had the last update 21 days ago. So they are not using the latest version of this repo. I do think it is an error in linguist's side.

**Comment by ukos-git** [comment]
ok. let's wait. It can even be possible that they rolled back the submodule on the servers that deploy the website. Our `tmlanguage` file seems to be good.

```igor
Make/N=(Highlighting) come:back
```

**Comment by t-b** [comment]
![grafik](https://user-images.githubusercontent.com/1185677/66169390-82e74200-e640-11e9-8d59-cd12edb484f6.png)

Seems to fixed on their end.
